// @ts-nocheck -- skip type checking
import * as docs_5 from "../content/docs/website-docs/README_EN.mdx?collection=docs&hash=1746087731371"
import * as docs_4 from "../content/docs/website-docs/README.mdx?collection=docs&hash=1746087731371"
import * as docs_3 from "../content/docs/website-docs/DEPLOY.mdx?collection=docs&hash=1746087731371"
import * as docs_2 from "../content/docs/popular-science-article/entering-tone.mdx?collection=docs&hash=1746087731371"
import * as docs_1 from "../content/docs/test.mdx?collection=docs&hash=1746087731371"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1746087731371"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/wangjingwen/Documents/GitHub/my-personal-docs/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"test.mdx","absolutePath":"/Users/wangjingwen/Documents/GitHub/my-personal-docs/content/docs/test.mdx"}, data: docs_1 }, { info: {"path":"popular-science-article/entering-tone.mdx","absolutePath":"/Users/wangjingwen/Documents/GitHub/my-personal-docs/content/docs/popular-science-article/entering-tone.mdx"}, data: docs_2 }, { info: {"path":"website-docs/DEPLOY.mdx","absolutePath":"/Users/wangjingwen/Documents/GitHub/my-personal-docs/content/docs/website-docs/DEPLOY.mdx"}, data: docs_3 }, { info: {"path":"website-docs/README.mdx","absolutePath":"/Users/wangjingwen/Documents/GitHub/my-personal-docs/content/docs/website-docs/README.mdx"}, data: docs_4 }, { info: {"path":"website-docs/README_EN.mdx","absolutePath":"/Users/wangjingwen/Documents/GitHub/my-personal-docs/content/docs/website-docs/README_EN.mdx"}, data: docs_5 }], [{"info":{"path":"popular-science-article/meta.json","absolutePath":"/Users/wangjingwen/Documents/GitHub/my-personal-docs/content/docs/popular-science-article/meta.json"},"data":{"title":"科普文章","description":"奇奇怪怪的小知识","root":true,"icon":"Notebook"}}, {"info":{"path":"website-docs/meta.json","absolutePath":"/Users/wangjingwen/Documents/GitHub/my-personal-docs/content/docs/website-docs/meta.json"},"data":{"title":"网站文档","pages":["---README 文件---","README","README_EN","---部署指南---","DEPLOY"],"description":"有关本网站部署、开发、维护的文档集合","root":true,"icon":"Cog"}}])